name: 자동 테스트

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Github에서 제공하는 최신 ubuntu 리눅스 환경 사용

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 이거 안 하면 권한 오류 발생
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew build